#! /usr/bin/env node
// -*- js -*-

/*global process,require,JSON*/
(function setUp(process, require, JSON) {
  'use strict';

  var npmConf = require('../package.json')
    , bowerConf = require('../bower.json')
    , fs = require('fs');

  bowerConf.version = npmConf.version;
  fs.writeFileSync('../bower.json', JSON.stringify(bowerConf));
}(process, require, JSON));
